# -*- mode: python ; coding: utf-8 -*-

# DevToolBox 后端打包配置
a = Analysis(
    ['backend/app.py'],
    pathex=['backend'],
    binaries=[],
    datas=[
        ('backend/static', 'static'),
    ],
    hiddenimports=[
        'modules.file_upload',
        'modules.json_tools',
        'modules.yaml_tools',
        'modules.markdown_tools',
        'modules.base64_tools',
        'modules.hash_tools',
        'modules.url_tools',
        'modules.timestamp_tools',
        'modules.data_conversion',
        'modules.data_conversion_styles',
        'modules.qr_tools',
        'modules.crypto_tools',
        'utils',
        'utils.ssrf_protection',
        'utils.path_safety',
        'utils.error_handler',
        'flask_cors',
        'yaml',
        'markdown',
        'markdown_it',
        'bcrypt',
        'pytz',
        'tzlocal',
        'bs4',
        'html2text',
        'fitz',
        'qrcode',
        'PIL',
        'hashlib',
        'hmac',
        'secrets',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.serialization',
        'Crypto',
        'Crypto.Cipher',
        'Crypto.PublicKey',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'unittest', 'test', 'tests', 'matplotlib', 'numpy', 'scipy', 'pandas', 'IPython', 'notebook'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DevToolBox',
    icon='frontend/public/favicon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,

)
